name: Fetch Twitch Data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: apps/twitch-db-async-fetcher/package-lock.json

    - name: Install dependencies
      working-directory: apps/twitch-db-async-fetcher
      run: npm install --production

    - name: Run script
      working-directory: apps/twitch-db-async-fetcher
      run: npm start
      env:
        TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
        TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
    
    - name: Add file to another repository
      env:
        TARGET_REPO_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: |
        # Configure Git with credentials
        cd apps/twitch-db-async-fetcher/dist

        # Clone the target repository
        git clone https://x-access-token:${{secrets.REPO_ACCESS_TOKEN}}@github.com/pajelonek/twitch-statistics-db.git target-db

        # Copy all files from twitchDir to the target repository
        mkdir -p target-db/twitch
        mkdir -p target-db/kick
        
        cp -r twitch/twitchDir/* target-db/twitch/
        cp -r kick/kickDir/* target-db/kick/

        # Go to the repository dir
        cd target-db

        # Configure Git with credentials
        git config user.name "twitch-statistics-bot"
        git config user.email "actions@github.com"

        # Add, commit, and push changes
        git add .
        git commit -m "Add new data files from twitch"
        git push https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/pajelonek/twitch-statistics-db.git master