name: Deploy static content to Pages

on:
  push:
    branches: ['master']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        working-directory: apps/twitch-statistics-page
        run: npm install
      - name: Build
        working-directory: apps/twitch-statistics-page
        run: npm run build
      - name: Deploy
        working-directory: apps/twitch-statistics-page
        run: npm run deploy